apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rails-hpa
  namespace: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rails
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

# optional
# - type: Pods
#   pods:
#     metric:
#       name: http_requests_per_second
#     target:
#       type: AverageValue
#       averageValue: "10"