apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sidekiq-hpa
  namespace: sidekiq
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sidekiq
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Pods
      pods:
        metric:
          name: sidekiq_queue_length
        target:
          type: AverageValue
          averageValue: "5"

# optional for sedekiq-exxporter
# metrics:
#   - type: Pods
#     pods:
#       metric:
#         name: sidekiq_queues_size
#       target:
#         type: AverageValue
#         averageValue: "5"