apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
  namespace: sidekiq
  labels:
    app: sidekiq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
        - name: sidekiq
          image: ghcr.io/your-org/your-app:latest
          command: [ "./entrypoints/docker-entrypoint.sh" ]
          args: [ "sidekiq" ]
          env:
            - name: REDIS_URL
              value: redis://redis-master.redis.svc.cluster.local:6379
            - name: RAILS_ENV
              value: production
            - name: SIDEKIQ_PROMETHEUS_EXPORTER
              value: "true"
          ports:
            - containerPort: 9394
              name: metrics
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: sidekiq-metrics
  namespace: sidekiq
  labels:
    app: sidekiq
spec:
  ports:
    - port: 9394
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: sidekiq